### PR TITLE
Options for GCFFlasher

### PR DESCRIPTION
**Pull request by Jo-Be-Co**
@phdelodder. Here you find the changes mentioned in #318. Thanks for testing.
I assumed the PR would be more slim as I just cherry-picked my 4 commits ...

----
On invocation of the update-script you could additionally add options:

```bash
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz <option1> <value1> <option2> <value2> ...
```

These options will be read by the script and checked against the possible options of the `GCFFlasher_internal`. Using this mechanism one could specify values for `device-name`, `timeout`, `retries` or the `loglevel`.
Additionally the script defines a default of 60 seconds for the timeout-parameter.

### CODE REVIEW

**Comment by phdelodder** [comment]
I would prefer you cherry pick just your own commits, can you also include a description in to README?

**Comment by Jo-Be-Co** [comment]
This is what I was trying to do ;-). Setting my fork to the head, cherry pick the commits and initiate a pull request ...

I'll give it a second (and maybe a third) try. Do you think I need a new PR then? Anyhow - for testing this one will give you the changes I am proposing.

**Comment by phdelodder** [comment]
Perhapse rebase to a new branch based on the latest master and then cherry-pick you changes into that new branch. I'll hope to test it this weekend.

**Comment by phdelodder** [comment]
add reference to issue  #318

**Comment by Jo-Be-Co** [comment]
And I will also check why my changes to the `README.md` didn't make it into the PR. This one I edited directly on the github web (in my fork).

**Comment by Jo-Be-Co** [comment]
Did a new one with #376 - this one had too much alien commits inside ...

**Pull request closed without merging**
