### PR TITLE
Bump deCONZ to 2.05.34

### PR DESCRIPTION
**Pull request by oscar-b**

### CODE REVIEW

**Comment by marthoc** [comment]
Upgraded image to 2.05.35 - closing this PR.

**Comment by oscar-b** [comment]
@marthoc 2.05.35 is a beta release though?

**Comment by Kane610** [comment]
Most of 2.05 has been considered beta until recently. It is more important to let new firmware for conbee to be evaluated which have actually had issues introduced with newer releases

**Comment by manup** [comment]
Side note: we are currently planning the next stable release which will concentrate on open bugs and make sure firmware version 0x261F0500 will be installed (meaning downgrade from 0x26210500 which caused some troubles).

**Comment by oscar-b** [comment]
@manup sounds great, 0x262 was causing issues for me as well, with Hue and IKEA mixed. 0x261 seems much more stable.

**Comment by manup** [comment]
@marthoc it was added in 2.05.31, example usage: `--dev=/dev/ttyUSB1`

https://github.com/dresden-elektronik/deconz-rest-plugin/releases/tag/V2_05_31

**Pull request closed without merging**
