### PR TITLE
Bump deCONZ to 2.13.02 beta

### PR DESCRIPTION
**Pull request by phdelodder**

### CODE REVIEW

**Comment by Gloomyeye** [comment]
Could you update the docker image with the latest beta?

**Comment by phdelodder** [comment]
Travis is giving me issues

**Comment by andresvaher** [comment]
Is there an ETA on docker image to latest beta?

**Comment by phdelodder** [comment]
give we have issue with travis and can't reach marthoc, deconz community is moving: https://github.com/deconz-community/deCONZ-Docker

**Comment by xconverge** [comment]
@phdelodder is this new image ready to use? I am not able to get my network up fully with it so will just build myself locally until we get the goahead to use it

**Comment by phdelodder** [comment]
For the migration to the new docker image, the repo has changed and the volume:
- image: marthoc/deconz -> deconzcommunity/deconz
- volume: /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ --> /opt/deconz:/opt/deCONZ
If these 2 are changed then the migration shouldn't have an impact

**Comment by phdelodder** [comment]
@xconverge it's ready to use.

**Pull request closed without merging**
