### PR TITLE
Add environment variable to allow use of Docker secret as VNC password

### LINKED ISSUE #242: VNC password file support for use with docker secrets
A small update in the start.sh would make it possible to use a docker secret for the VNC password:

```
  # Set VNC password
  if [ "$DECONZ_VNC_PASSWORD_FILE" != 0 ]; then
      cat "$DECONZ_VNC_PASSWORD_FILE" | tigervncpasswd -f > /root/.vnc/passwd
  else
    echo "$DECONZ_VNC_PASSWORD" | tigervncpasswd -f > /root/.vnc/passwd
  fi
  chmod 600 /root/.vnc/passwd
```

### PR DESCRIPTION
**Pull request by mingan666**
Adds environment variable DECONZ_VNC_PASSWORD_FILE to allow user to create a Docker secret and point the environment variable at the secret file to avoid passing VNC password in plaintext on the command line to the DECONZ_VNC_PASSWORD env var.

Closes #242.

### CODE REVIEW

**Comment by marthoc** [comment]
@mingan666 I am OK with merging this, but please explain a bit more clearly, and we will need to add another explanation to the README so that users know how to use it. 

I assume if you are saying this works with docker secret then you will also need to specify `--secret name_of_secret`, and then the environment variable would get set to `-e DECONZ_VNC_PASSWORD_FILE=/run/secrets/name_of_secret`. Am I right? Please clarify as I would like to get this merged into the larger update I am doing now.

**Comment by mingan666** [comment]
I think you'll need to run docker in swarm mode to be able to use docker secrets. I'm using a docker swarm with only one node in it (being able to use secrets is one of the reasons why I do so). Fixing that's not very deconz specific so I leave that out.

Need to create a docker secret to use:

`
$ printf <password> | docker secret create home-vnc-password -
`

These are the important parts from my stack yml file (not sure how to get this shown as a code block?):
`
services:
  deconz:
    image: marthoc/deconz:amd64-2.05.78
    volumes:
     <the usual deconz stuff>
    environment:
     <the usual deconz stuff>
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD_FILE=/run/secrets/deconz-vnc-password
    ports:
     <the usual deconz stuff>
    secrets:
      - deconz-vnc-password

secrets:
  deconz-vnc-password:
    external: true
`

Then you need to use docker stack commands:
`
docker stack deploy -c <yml file> <stack name>
`

**Comment by mingan666** [comment]
I can try to add an example to the readme file tomorrow if you want me to.

**Comment by mingan666** [comment]
@marthoc 
I've added more information to the README file. 
There are some special things to think about when it comes to docker swarm mode, but I did not think that fits in this repos README?
For example you need to do additional work to get the usb stuff to work. I did however include that into the yml file.
Please let me know what you think.

**Comment by marthoc** [comment]
After reviewing further, I like the idea, but I don't think it's ready to merge just yet. I would want to see the script to check if the file is available, etc., and fallback to using the VNC_PASSWORD env var. I need to think a bit further about this. Will merge in the future. Thanks!

**Comment by mingan666** [comment]
@marthoc 
I see you closed the request? 
I like you're idea, but I guess you do not want me to update the scripts accordingly?

**Pull request closed without merging**
